@startuml
hide <<Path>> circle
hide <<Response>> circle
hide <<Parameter>> circle
hide empty methods
hide empty fields
skinparam class {
BackgroundColor<<Path>> Wheat
}
set namespaceSeparator none

class "Route" {
  {field} name : string
}

class "RouteSegment" {
  {field} discriminator : string
  {field} from : string
  {field} to : string
  {field} duration : integer {O}
}

class "HikingSegment" {
}

class "MountainRideSegment" {
}

class "ClimbingSegmentDetails" {
  {field} height : integer
  {field} difficulty : string {O}
}

class "HikingSegmentDetails" {
  {field} length : integer
  {field} difficulty : string {O}
}

class "MountainRideSegmentDetails" {
  {field} costs : integer
}

class "RouteResponse" <<Response>>  {
}

class "getRoutes" <<Path>>  <<GET /api/routes/{id}>>  {
  {field} id : string
}

"Route" --> "*" "RouteSegment"  :  "routeSegments"

"Route" --> "0..1" "RouteSegment"  :  "mostDifficultRouteSegment"

"HikingSegment" --> "1" "RouteSegment"

"HikingSegment" --> "1" "HikingSegmentDetails"

"MountainRideSegment" --> "1" "RouteSegment"

"MountainRideSegment" --> "1" "MountainRideSegmentDetails"

"RouteResponse" --> "1" "Route"

"getRoutes" ..> "1" "RouteResponse"  :  "200"

@enduml